INSERT INTO CLIENTS (NAME) VALUES('Test1');
INSERT INTO CLIENTS (NAME) VALUES('Test2');
INSERT INTO CLIENTS (NAME) VALUES('Test3');
INSERT INTO CLIENTS (NAME) VALUES('Test4');

INSERT INTO ACCOUNTS (CLIENT_ID, NUMBER, CURRENCY, BALANCE) VALUES(1, 11, 'RUB', 0);
INSERT INTO ACCOUNTS (CLIENT_ID, NUMBER, CURRENCY, BALANCE) VALUES(1, 12, 'RUB', 10);
INSERT INTO ACCOUNTS (CLIENT_ID, NUMBER, CURRENCY, BALANCE) VALUES(2, 21, 'RUB', 100);
INSERT INTO ACCOUNTS (CLIENT_ID, NUMBER, CURRENCY, BALANCE) VALUES(2, 22, 'RUB', 22);
INSERT INTO ACCOUNTS (CLIENT_ID, NUMBER, CURRENCY, BALANCE) VALUES(3, 31, 'RUB', 31);

INSERT INTO CARDS (NUMBER, ACCOUNT_ID) VALUES ( '1234 5678 9012 1234', 1);
INSERT INTO CARDS (NUMBER, ACCOUNT_ID) VALUES ( '1234 5678 9012 1235', 1);
INSERT INTO CARDS (NUMBER, ACCOUNT_ID) VALUES ( '1234 5678 9012 1236', 1);


